version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: watguessr-postgres
    environment:
      POSTGRES_DB: watguessr
      POSTGRES_USER: watuser
      POSTGRES_PASSWORD: goon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watuser -d watguessr"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 