-- WatGuessr Database Initialization

GRANT ALL ON SCHEMA public TO watuser;
GRANT ALL ON ALL TABLES IN SCHEMA public TO watuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO watuser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO watuser;

-- set default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO watuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO watuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO watuser;