app:
  name: WatGuessr

server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.default_schema: watguessr

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: default
    default-schema: watguessr
    liquibase-schema: watguessr

aws:
  region: ${AWS_REGION:us-east-2}
  s3:
    bucket:
      name: ${AWS_S3_BUCKET_NAME:watguessr}
  profile: ${AWS_PROFILE:watguessr-dev}


# # 1. Install AWS CLI (if not already installed) run these commands in the terminal
# # macOS
# brew install awscli
# # Windows: Download from https://aws.amazon.com/cli/
# # Linux: Use curl command from AWS docs

# # 2. Configure AWS CLI with your credentials
# aws configure --profile watguessr-dev

# # They'll be prompted for:
# AWS_ACCESS_KEY_ID=AKIAQC5YHNSIYIKXVF5X
# AWS_SECRET_ACCESS_KEY=mk6AJKoNY/ueTnlS07cjkBLeIwuCc8YXIA3aEhO7
# AWS_REGION=us-east-2
# AWS_S3_BUCKET_NAME=watguessr

# # 3. Set environment variable
# export AWS_PROFILE=watguessr-dev

# # 4. Test AWS access
# aws s3 ls s3://watguessr/watguessr-s3/ --profile watguessr-dev
