app:
  name: WatGuessr

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/watguessr?currentSchema=watguessr
    username: watuser
    password: goon
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.default_schema: watguessr

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: default
    default-schema: watguessr
    liquibase-schema: watguessr
