app:
  name: WatGuessr

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/watguessr?currentSchema=watguessr
    username: watuser
    password: goon
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: wukenny0126@gmail.com
    password: xmnxqipnevhqdydu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.default_schema: watguessr

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: default
    default-schema: watguessr
    liquibase-schema: watguessr

# JWT Configuration
jwt:
  issuer: watguessr
  ttl: 86400 # 24 hours in seconds
  # RSA Keys for JWT signing (in src/main/resources/jwt/)
  private-key: classpath:jwt/private-key.pem
  public-key: classpath:jwt/public-key.pem
