package com.gooners.watguessr.service;

import java.time.Duration;
import java.time.Instant;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.jwt.JwtClaimsSet;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;
import org.springframework.stereotype.Service;

import com.gooners.watguessr.entity.User;

@Service
public class JwtService {

    private final JwtEncoder jwtEncoder;
    private final String issuer;
    private final long ttlSeconds;

    public JwtService(
            JwtEncoder jwtEncoder,
            @Value("${JWT_ISSUER:watguessr}") String issuer,
            @Value("${JWT_TTL:86400}") long ttlSeconds
    ) {
        this.jwtEncoder = jwtEncoder;
        this.issuer = issuer;
        this.ttlSeconds = ttlSeconds;
    }

    //Token is Generated Separately
    //The JWT token is generated by the JwtService and contains:
    //Subject: The username
    //Issuer: Your app name ("watguessr")
    //Expiration: 24 hours from creation (or 30 days if remember me)
    //Claims: Any additional user data you want to embed
    public String generateToken(Authentication authentication) {
        return generateToken(authentication, false);
    }

    public String generateToken(Authentication authentication, boolean rememberMe) {
        String username = authentication.getName();

        // Extract the single role from authenticated user
        String role = authentication.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .findFirst()
                .orElse("ROLE_USER"); // fallback if none found

        // Use 30 days for remember me, otherwise use default TTL
        long tokenTtl = rememberMe ? 2592000 : ttlSeconds; // 30 days or default

        // Build claims with single role
        final var claimsSet = JwtClaimsSet.builder()
                .subject(username)
                .issuer(issuer)
                .expiresAt(Instant.now().plus(Duration.ofSeconds(tokenTtl)))
                .claim("role", role)
                .build();

        return jwtEncoder.encode(JwtEncoderParameters.from(claimsSet))
                .getTokenValue();
    }

    // Generate token for Google OAuth user
    public String generateTokenForUser(User user) {
        final var claimsSet = JwtClaimsSet.builder()
                .subject(user.getUsername())
                .issuer(issuer)
                .expiresAt(Instant.now().plus(Duration.ofSeconds(ttlSeconds)))
                .claim(
                        "role",
                        user.getEmailAddress().equals("watguessr@gmail.com")
                                ? "ROLE_ADMIN"
                                : "ROLE_USER"
                )
                .claim("email", user.getEmailAddress())
                .build();

        return jwtEncoder.encode(JwtEncoderParameters.from(claimsSet))
                .getTokenValue();
    }
}
