package com.gooners.watguessr.service;

import java.time.Duration;
import java.time.Instant;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.jwt.JwtClaimsSet;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;
import org.springframework.stereotype.Service;

@Service
public class JwtService {

    private final JwtEncoder jwtEncoder;
    private final String issuer;
    private final long ttlSeconds;

    public JwtService(
            JwtEncoder jwtEncoder,
            @Value("${JWT_ISSUER:watguessr}") String issuer,
            @Value("${JWT_TTL:86400}") long ttlSeconds
    ) {
        this.jwtEncoder = jwtEncoder;
        this.issuer = issuer;
        this.ttlSeconds = ttlSeconds;
    }

    //Token is Generated Separately
    //The JWT token is generated by the JwtService and contains:
    //Subject: The username
    //Issuer: Your app name ("watguessr")
    //Expiration: 24 hours from creation
    //Claims: Any additional user data you want to embed
    public String generateToken(Authentication authentication) {
        String username = authentication.getName();

        // Extract the single role from authenticated user
        String role = authentication.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .findFirst()
                .orElse("ROLE_USER"); // fallback if none found

        // Build claims with single role
        final var claimsSet = JwtClaimsSet.builder()
                .subject(username)
                .issuer(issuer)
                .expiresAt(Instant.now().plus(Duration.ofSeconds(ttlSeconds)))
                .claim("role", role)
                .build();

        return jwtEncoder.encode(JwtEncoderParameters.from(claimsSet))
                .getTokenValue();
    }
}
